### PR TITLE
it was a really slow episode of the walking dead

### PR DESCRIPTION
**Pull request by Daniel-Warner-X**

### CODE REVIEW

**Comment by Bachmann1234** [comment]
This has made my day! Thanks

**Comment by Bachmann1234** [comment]
How have you been btw?

**Comment by Daniel-Warner-X** [comment]
I've been great, thanks. I do, however, occasionally miss Smash O'Clock :)

How are things with you?

On Sun, Nov 8, 2015 at 11:20 PM, Matt Bachmann <notifications@github.com>
wrote:

> How have you been btw?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bachmann1234/bachmann1234.github.io/pull/1#issuecomment-154915731>
> .
>



-- 
*Daniel Warner*
Director of User Experience
---------------------------------------------
« Twitter <https://twitter.com/dw_ux> »
---------------------------------------------
« LinkedIn <https://www.linkedin.com/in/danielwarnerXD> »
---------------------------------------------

**Comment by Bachmann1234** [comment]
Doing pretty well. Yeah, we still do that. I took the mantle of Link to keep Damir in his place ;-)

**Pull request merged**
